{{- if and .Values.grafana.enabled .Values.grafana.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: guestbook
spec:
  to:
    kind: Service
    name: grafana
  port:
    targetPort: http
  {{- if .Values.grafana.route.host }}
  host: {{ .Values.grafana.route.host }}
  {{- end }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
