{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: guestbook
type: Opaque
stringData:
  admin-user: "{{.Values.grafana.adminUser}}"
  admin-password: "{{.Values.grafana.adminPassword}}"
{{- end }}
