apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: guestbook
type: Opaque
stringData:
  REDIS_PASSWORD: "{{.Values.redis.auth.password}}"
