apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/part-of: guestbook
data:
  DB_HOST: "{{ .Values.backend.env.dbHost }}"
  DB_PORT: "{{ .Values.backend.env.dbPort }}"
  REDIS_HOST: "{{ .Values.backend.env.redisHost }}"
  REDIS_PORT: "{{ .Values.backend.env.redisPort }}"
