apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: guestbook
data:
  nginx.conf: |
{{ (.Files.Get "frontend/nginx.conf") | indent 4 }}
