apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: guestbook
type: Opaque
stringData:
  POSTGRESQL_USER: "{{ .Values.postgres.auth.username }}"
  POSTGRESQL_PASSWORD: "{{ .Values.postgres.auth.password }}"
  POSTGRESQL_DATABASE: "{{ .Values.postgres.auth.database }}"
